import {chromium} from 'playwright';import fs from 'node:fs';
const results=[];let browser;
const variants=process.env.ASTRA_ABLATIONS?[
 ['balanced',{quality:'balanced'}],['dpr-1',{quality:'balanced',dpr:1}],['no-post',{quality:'balanced',post:false}],['no-particles',{quality:'balanced',particles:false}],['no-updates',{quality:'balanced',updates:false}],['simple-materials',{quality:'balanced',materials:false}],['no-story',{quality:'balanced',story:false}],['low',{quality:'low'}],['high',{quality:'high'}]
]:[['auto',{}]];
try{for(const mode of [{mobile:false,rate:1},{mobile:false,rate:4},{mobile:true,rate:4}])for(const [variant,profile] of variants){
 browser=await chromium.launch({channel:'chrome',headless:true});const {mobile,rate}=mode;const ctx=await browser.newContext({viewport:{width:mobile?390:1440,height:1000},isMobile:mobile,hasTouch:mobile});await ctx.route('**/api/v1/auth/me',r=>r.fulfill({status:401,json:{detail:{code:'auth_required'}}}));await ctx.addInitScript(profile=>{window.__ASTRA_PROFILE__=profile;window.gate={ready:0,poster:0,longTasks:[]};new PerformanceObserver(l=>l.getEntries().forEach(e=>window.gate.longTasks.push({start:e.startTime,duration:e.duration}))).observe({type:'longtask',buffered:true});const observe=()=>{const pic=document.querySelector('.core-fallback img');if(pic?.complete&&pic.naturalWidth&&!window.gate.poster)window.gate.poster=performance.now();if(!window.gate.ready&&document.querySelector('.core-visual[data-state="webgl"]'))window.gate.ready=performance.now();};new MutationObserver(observe).observe(document,{subtree:true,attributes:true,childList:true});document.addEventListener('load',observe,true);},profile);
 const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));if(rate>1){const cdp=await ctx.newCDPSession(p);await cdp.send('Emulation.setCPUThrottlingRate',{rate});}
 await p.goto(process.env.ASTRA_GATE_URL||'http://127.0.0.1:4191/');await p.locator('.core-visual[data-state="webgl"]').waitFor({timeout:30000});await p.waitForTimeout(2000);
 const sample=await p.evaluate(async mobile=>{const shell=document.querySelector('.immersive-shell'),story=document.querySelector('.core-story'),canvas=document.querySelector('canvas');const startY=mobile?Math.max(0,canvas.getBoundingClientRect().top+scrollY-innerHeight*.55):story.getBoundingClientRect().top+scrollY-innerHeight*.55,endY=mobile?canvas.getBoundingClientRect().bottom+scrollY-innerHeight*.35:shell.getBoundingClientRect().bottom+scrollY-innerHeight*.9;scrollTo(0,startY);await new Promise(r=>setTimeout(r,600));const start=performance.now(),frame=Number(canvas.dataset.frameCount),samples=[];let last=start;await new Promise(resolve=>{function tick(now){const t=Math.min(1,(now-start)/8000),phase=t<.5?t*2:(1-t)*2;scrollTo(0,startY+(endY-startY)*phase);samples.push({dt:now-last,visible:(canvas.getBoundingClientRect().bottom>0&&canvas.getBoundingClientRect().top<innerHeight),frame:Number(canvas.dataset.frameCount),scene:Number(canvas.dataset.sceneUpdateMs||0),render:Number(canvas.dataset.renderSubmitMs||0),quality:canvas.dataset.quality});last=now;if(t<1)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});const elapsed=performance.now()-start,percentile=(a,q)=>a.sort((a,b)=>a-b)[Math.floor(a.length*q)];const active=samples.filter(s=>s.visible),activeMs=active.reduce((a,s)=>a+s.dt,0);let activeFrames=0;for(let i=1;i<samples.length;i++)if(samples[i].visible&&samples[i-1].visible)activeFrames+=Math.max(0,samples[i].frame-samples[i-1].frame);return {activeSceneFPS:activeFrames*1000/activeMs,activeMs,sceneFPS:(Number(canvas.dataset.frameCount)-frame)*1000/elapsed,rafFPS:samples.length*1000/elapsed,p95:percentile(samples.map(s=>s.dt),.95),sceneUpdateP95:percentile(samples.map(s=>s.scene),.95),renderSubmitP95:percentile(samples.map(s=>s.render),.95),qualityHistory:[...new Set(samples.map(s=>s.quality))],metrics:window.__ASTRA_METRICS__,diagnostics:{...canvas.dataset},...window.gate,marks:performance.getEntriesByType('mark').filter(m=>m.name.startsWith('astra:')).map(m=>({name:m.name,time:m.startTime})),overflow:document.documentElement.scrollWidth>innerWidth,scrollLongTasks:window.gate.longTasks.filter(e=>e.start>start)};},mobile);
 if(profile.updates===false){sample.sceneFPS=null;sample.activeSceneFPS=null;}results.push({mode:mobile?'390 touch CPU x4':rate===4?'1440 desktop CPU x4':'1440 desktop',variant,...sample,errors});console.log(JSON.stringify({mode:results.at(-1).mode,variant,ready:sample.ready,poster:sample.poster,fps:sample.sceneFPS,p95:sample.p95}));await ctx.close();await browser.close();browser=undefined;
 }fs.writeFileSync(process.env.ASTRA_GATE_OUTPUT||'../work/immersive/gate-after-full.json',JSON.stringify(results,null,2));}finally{await browser?.close();}
