"""PostgreSQL import lifecycle"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '6d131c25bdd2'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Integer(), nullable=False),
    sa.Column('invalid', sa.Integer(), nullable=False),
    sa.Column('duplicate', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'completed') = (committed_at IS NOT NULL)", name='ck_import_committed'),
    sa.CheckConstraint("status IN ('uploaded','mapped','analyzed','completed')", name='ck_import_status'),
    sa.CheckConstraint("status NOT IN ('analyzed','completed') OR total = valid + invalid + duplicate", name='ck_import_partition'),
    sa.CheckConstraint('total >= 0 AND valid >= 0 AND invalid >= 0 AND duplicate >= 0 AND inserted >= 0 AND inserted <= valid', name='ck_import_counts'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_workspace_created', 'imports', ['workspace_id', 'created_at', 'id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("classification IS NULL OR classification IN ('valid','invalid','duplicate')", name='ck_row_classification'),
    sa.CheckConstraint('row_number >= 2', name='ck_row_number'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'row_number', name='uq_row_number')
    )
    op.create_index('ix_row_import_classification', 'import_rows', ['import_id', 'classification'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('import_id', sa.Uuid(), nullable=False),
    sa.Column('source_row_id', sa.Uuid(), nullable=True),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('email_normalized = lower(btrim(email_normalized)) AND length(email_normalized) > 0', name='ck_lead_email_normalized'),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_row_id'], ['import_rows.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_normalized'),
    sa.UniqueConstraint('source_row_id')
    )
    op.create_index('ix_lead_workspace_created', 'leads', ['workspace_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_leads_import_id'), 'leads', ['import_id'], unique=False)
    op.create_table('validation_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['row_id'], ['import_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_id', 'field', 'code', name='uq_issue')
    )
    op.create_index(op.f('ix_validation_issues_row_id'), 'validation_issues', ['row_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_issues_row_id'), table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index(op.f('ix_leads_import_id'), table_name='leads')
    op.drop_index('ix_lead_workspace_created', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_row_import_classification', table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index('ix_import_workspace_created', table_name='imports')
    op.drop_table('imports')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
