import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';
const base=process.env.ASTRASYNQ_PREVIEW_URL||'http://127.0.0.1:4185';
const dictionaries=Object.fromEntries(['en','uk','ru'].map(l=>[l,JSON.parse(fs.readFileSync(new URL(`../src/locales/${l}.json`,import.meta.url),'utf8'))]));
const output=process.env.ASTRASYNQ_QA_OUTPUT||path.resolve('..','.clearance','app');fs.mkdirSync(output,{recursive:true});let browser;let qaPassword;
before(async()=>{const {execFileSync}=await import('node:child_process');const python=process.env.ASTRASYNQ_PYTHON||path.resolve('..','.venv',process.platform==='win32'?'Scripts':'bin',process.platform==='win32'?'python.exe':'python');qaPassword=JSON.parse(execFileSync(python,['tests/browser_seed.py'],{cwd:path.resolve('..','backend'),env:{...process.env,PYTHONPATH:path.resolve('..','backend'),DATABASE_URL:process.env.TEST_DATABASE_URL||'postgresql+psycopg://astrasynq@127.0.0.1:55432/astrasynq_test'}}).toString()).password;browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true});const probe=await browser.newContext();try{await loginContext(probe);console.log(`Auth preflight PASS through ${base}: CSRF, login, session and admin seed`);}finally{await probe.close();}});after(async()=>{await browser?.close();});
async function context(lang='en',reducedMotion='reduce'){const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion});await ctx.addInitScript(l=>localStorage.setItem('astrasynq.language',l),lang);await freshSample(ctx);await loginContext(ctx);return ctx;}
const qaStates={};
async function authJson(response,expectedStatus,label){
 const body=await response.text(),type=response.headers()['content-type']||'';
 const diagnostic=`${label}: url=${response.url()} status=${response.status()} content-type=${type||'<missing>'} body-length=${body.length}. Check preview API proxy, server readiness and test database.`;
 assert.equal(response.status(),expectedStatus,diagnostic);
 assert(type.includes('application/json'),diagnostic);
 assert(body.length>0,diagnostic);
 try{return JSON.parse(body);}catch{assert.fail(diagnostic+' Invalid JSON.');}
}
async function loginContext(ctx,role='admin'){
 if(qaStates[role]){await ctx.addCookies(qaStates[role]);if((await ctx.request.get(base+'/api/v1/auth/me')).status()===200)return;delete qaStates[role];}
 const pre=await ctx.request.get(base+'/api/v1/auth/csrf');
 const bootstrap=await authJson(pre,200,'CSRF bootstrap');
 assert.equal(typeof bootstrap.csrf_token,'string','CSRF token missing');
 assert(bootstrap.csrf_token.length>0,'CSRF token empty');
 const res=await ctx.request.post(base+'/api/v1/auth/login',{headers:{'X-CSRF-Token':bootstrap.csrf_token},data:{email:`qa-${role}@example.test`,password:qaPassword}});
 await authJson(res,200,'QA login');
 const identity=await authJson(await ctx.request.get(base+'/api/v1/auth/me'),200,'Authenticated session');
 assert.equal(identity.role,role,'Unexpected test role');
 qaStates[role]=(await ctx.storageState()).cookies;
 assert(qaStates[role].some(cookie=>cookie.name==='astrasynq_session'&&cookie.httpOnly),'Session cookie missing');
}
async function freshSample(ctx){const suffix=Date.now().toString(36)+Math.random().toString(36).slice(2);await ctx.route('**/api/v1/samples/leads.csv',async route=>{const response=await route.fetch();const body=(await response.text()).replace(/([A-Za-z0-9._+-]+)@example\.com/g,(all,name)=>name==='alex'?all:`${name}.${suffix}@example.com`);await route.fulfill({response,body});});}
async function screenshot(p,name){await p.screenshot({path:path.join(output,name+'.png'),fullPage:true});}
async function responsive(p,name,lang){for(const width of [1440,1024,768,390]){await p.setViewportSize({width,height:1000});await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),`overflow ${name} ${lang} ${width}`);if(await p.locator('.sidebar nav').count())assert(await p.locator('.sidebar nav a[href="#/automations"]').isVisible(),`automations navigation ${lang} ${width}`);if(width===390||width===1440)await screenshot(p,`${name}-${lang}-${width}`);}await p.setViewportSize({width:1440,height:1000});}
test('dictionary parity and translations for all six validation codes',()=>{for(const l of ['uk','ru'])assert.deepEqual(Object.keys(dictionaries[l]).sort(),Object.keys(dictionaries.en).sort());for(const l of ['en','uk','ru'])for(const code of ['invalid_email','negative_amount','duplicate_record','required_field','invalid_date','invalid_currency'])assert(dictionaries[l][code]);});
for(const lang of ['en','uk','ru'])test(`${lang}: all screens, review errors, responsive and import regression`,async()=>{
 const ctx=await context(lang);const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const d=dictionaries[lang];
 await p.goto(base);await p.locator('h1').waitFor();assert.equal(await p.locator('html').getAttribute('lang'),lang);assert((await p.locator('h1').innerText()).includes(d['Messy data.']));for(const section of await p.locator('main > section').all())await section.scrollIntoViewIfNeeded();await p.evaluate(()=>window.scrollTo(0,0));await screenshot(p,`landing-${lang}-1440`);await responsive(p,'landing',lang);
 await p.goto(base+'/#/overview');await p.locator('.metric-card').first().waitFor();assert((await p.locator('h1').innerText()).includes(d.Overview));assert((await p.locator('.metric-quality').innerText()).includes(d['Data quality']));assert((await p.locator('.metric-card').nth(3).innerText()).includes(d.Connections));await screenshot(p,`dashboard-${lang}-1440`);await responsive(p,'dashboard',lang);
 const baseline=await p.evaluate(async()=>{return (await fetch('/api/v1/dashboard/summary')).json();});await p.goto(base+'/#/import');await responsive(p,'upload',lang);await p.getByRole('button',{name:d['Use sample'],exact:true}).click();await p.locator('.mapping-panel').waitFor();await responsive(p,'mapping',lang);await p.getByRole('button',{name:d['Validate records'],exact:true}).click();await p.locator('.review-panel').waitFor();const statRatios=await p.locator('.review-stats strong,.review-stats span').evaluateAll(elements=>{const lum=s=>{const c=s.match(/[\d.]+/g).slice(0,3).map(Number).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return .2126*c[0]+.7152*c[1]+.0722*c[2];};return elements.map(el=>{const a=lum(getComputedStyle(el).color),b=lum(getComputedStyle(el.parentElement).backgroundColor);return {ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),required:el.tagName==='STRONG'?3:4.5};});});assert(statRatios.every(x=>x.ratio>=x.required),'review contrast');assert.deepEqual(await p.locator('.review-stats strong').allTextContents(),['12','8','2','2']);assert((await p.locator('.review-notice').innerText()).includes(d['review.import'].replace('{count}','8')));for(const code of ['invalid_email','negative_amount','duplicate_record'])assert((await p.locator('.review-table').innerText()).includes(d[code]));await p.reload();await p.locator('.review-panel').waitFor();assert.deepEqual(await p.locator('.review-stats strong').allTextContents(),['12','8','2','2']);await screenshot(p,`review-${lang}-1440`);await responsive(p,'review',lang);
 await p.getByRole('button',{name:d['import.action'].replace('{count}','8'),exact:true}).click();await p.locator('.complete-panel').waitFor();await responsive(p,'complete',lang);assert((await p.locator('.complete-panel').innerText()).includes(d['complete.result'].replace('{count}','8')));await p.goto(base+'/#/overview');await p.locator('.metric-card').first().waitFor();assert.equal(await p.locator('.metric-card strong').first().innerText(),String(baseline.record_count+8));assert.equal(await p.locator('.metric-card strong').nth(1).innerText(),String(baseline.import_count+1));assert.deepEqual(errors,[]);await ctx.close();
});
test('switching persists on reload and preserves Wizard review state',async()=>{const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await freshSample(ctx);await loginContext(ctx);const p=await ctx.newPage();await p.goto(base);assert.equal(await p.locator('html').getAttribute('lang'),'en');for(const [lang,name] of [['uk','Українська'],['ru','Русский'],['en','English']]){await p.locator('.language-trigger').click();await p.getByRole('menuitemradio',{name,exact:true}).click();assert.equal(await p.evaluate(()=>localStorage.getItem('astrasynq.language')),lang);await p.reload();assert.equal(await p.locator('html').getAttribute('lang'),lang);}await p.goto(base+'/#/import');await p.getByRole('button',{name:'Use sample',exact:true}).click();await p.getByRole('button',{name:'Validate records',exact:true}).click();await p.locator('.review-panel').waitFor();await p.locator('.language-trigger').click();await p.getByRole('menuitemradio',{name:'Українська',exact:true}).click();assert((await p.locator('.review-notice').innerText()).includes('8 записів буде імпортовано.'));await p.locator('.language-trigger').click();await p.getByRole('menuitemradio',{name:'Русский',exact:true}).click();assert((await p.locator('.review-notice').innerText()).includes('Будет импортировано 8 записей.'));await ctx.close();});
test('keyboard focus, dialog trap and reduced motion',async()=>{const ctx=await context();const p=await ctx.newPage();await p.goto(base);await p.locator('.language-trigger').focus();await p.keyboard.press('Enter');const button=p.getByRole('menuitemradio',{name:'Українська',exact:true});await button.focus();await p.keyboard.press('Enter');assert.equal(await p.locator('html').getAttribute('lang'),'uk');assert.equal(await p.locator('.language-trigger').evaluate(el=>getComputedStyle(el).outlineStyle),'solid');assert.equal(await p.locator('.immersive-shell').getAttribute('data-motion'),'reduced');assert.equal(await p.locator('.core-visual canvas').count(),0);assert.equal(await p.locator('[data-story-stage]').count(),7);await p.goto(base+'/#/overview');await p.getByRole('button',{name:'Інформація про демо',exact:true}).click();await p.getByRole('dialog').waitFor();assert(await p.getByRole('button',{name:'Закрити інформацію про демо'}).evaluate(el=>el===document.activeElement));await p.keyboard.press('Shift+Tab');assert(await p.getByRole('button',{name:'Зрозуміло'}).evaluate(el=>el===document.activeElement));await p.keyboard.press('Escape');assert.equal(await p.getByRole('dialog').count(),0);assert(await p.getByRole('button',{name:'Інформація про демо',exact:true}).evaluate(el=>el===document.activeElement));await ctx.close();});
test('decorative hero has no viewer controls',async()=>{const ctx=await context('en','no-preference');const p=await ctx.newPage();await p.goto(base);assert.equal(await p.locator('.core-controls button').count(),0);assert.equal(await p.locator('.immersive-shell').getAttribute('data-motion'),'running');await ctx.close();});
test('all six error codes render in each language from a real uploaded CSV',async()=>{
 const csv='email,amount,currency,created_at\nbad,,,\nnegative@example.com,-1,USD,\nalex@example.com,,,\nrequired@example.com,5,,\ndate@example.com,,,bad-date\ncurrency@example.com,,ZZZ,\n';
 const ctx=await context();const p=await ctx.newPage();await p.goto(base+'/#/import');await p.locator('#csv-file').setInputFiles({name:'errors.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await p.getByRole('button',{name:'Validate records',exact:true}).click();await p.locator('.review-panel').waitFor();
 for(const [lang,name] of [['en','English'],['uk','Українська'],['ru','Русский']]){await p.locator('.language-trigger').click();await p.getByRole('menuitemradio',{name,exact:true}).click();const text=await p.locator('.review-table').innerText();for(const code of ['invalid_email','negative_amount','duplicate_record','required_field','invalid_date','invalid_currency'])assert(text.includes(dictionaries[lang][code]),`${lang}: ${code}`);}await ctx.close();
});

for(const lang of ['en','uk','ru'])test(`${lang}: login, profile, users, logout and responsive auth`,async()=>{
 const d=dictionaries[lang];const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await ctx.addInitScript(l=>localStorage.setItem('astrasynq.language',l),lang);const p=await ctx.newPage();
 await p.goto(base+'/#/overview');await p.locator('.auth-card').waitFor();assert.equal(await p.locator('h1').innerText(),d['Sign in']);await responsive(p,'login',lang);
 await p.getByLabel(d.Email,{exact:true}).fill('qa-admin@example.test');await p.getByLabel(d.Password,{exact:true}).fill(qaPassword);await p.getByRole('button',{name:d['Sign in'],exact:true}).click();await p.locator('.metric-card').first().waitFor();assert((await p.locator('.profile-menu').innerText()).includes(d.admin));
 const cookies=await ctx.cookies();const session=cookies.find(c=>c.name==='astrasynq_session');assert(session.httpOnly && session.sameSite==='Lax');assert.equal(await p.evaluate(()=>document.cookie.includes('astrasynq_session')),false);
 await p.goto(base+'/#/users');await p.locator('.users-panel').first().waitFor();await responsive(p,'users',lang);await screenshot(p,`users-${lang}-1440`);
 await p.getByLabel(d.Email,{exact:true}).fill(`created-${lang}@example.test`);await p.getByLabel(d['Temporary password'],{exact:true}).fill(qaPassword);await p.getByRole('button',{name:d['Create user'],exact:true}).click();await p.getByRole('cell',{name:`created-${lang}@example.test`,exact:true}).waitFor();const row=p.getByRole('row').filter({hasText:`created-${lang}@example.test`});await row.locator('select').selectOption('operator');await p.waitForFunction(({email})=>document.querySelector(`select[aria-label*="${email}"]`)?.value==='operator',{email:`created-${lang}@example.test`});
 await p.getByLabel(d.Profile,{exact:true}).click();await p.getByRole('button',{name:d['Sign out'],exact:true}).click();await p.locator('.auth-card').waitFor();assert.equal((await ctx.request.get(base+'/api/v1/auth/me')).status(),401);assert.equal(await p.evaluate(()=>localStorage.getItem('astrasynq.active-import')),null);await ctx.close();
});

for(const role of ['viewer','operator'])test(`${role}: navigation, direct forbidden routes and backend enforcement`,async()=>{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await loginContext(ctx,role);const p=await ctx.newPage();await p.goto(base+'/#/overview');await p.locator('.metric-card').first().waitFor();assert.equal(await p.locator('nav a[href="#/users"]').count(),0);assert.equal(await p.locator('nav a[href="#/import"]').count(),role==='viewer'?0:1);
 await p.goto(base+'/#/users');await p.getByRole('heading',{name:'403 · Access denied'}).waitFor();if(role==='viewer'){await p.goto(base+'/#/import');await p.getByRole('heading',{name:'403 · Access denied'}).waitFor();}else{await p.goto(base+'/#/import');await p.locator('#csv-file').waitFor({state:'attached'});}
 const csrf=(await (await ctx.request.get(base+'/api/v1/auth/me')).json()).csrf_token;
 assert.equal((await ctx.request.post(base+'/api/v1/users',{headers:{'X-CSRF-Token':csrf},data:{email:'forbidden@example.test',password:qaPassword,role:'admin'}})).status(),403);
 assert.equal((await ctx.request.post(base+'/api/v1/auth/logout')).status(),403);assert.equal((await ctx.request.get(base+'/api/v1/leads/export.csv')).status(),200);await ctx.close();
});

test('expired or revoked browser session returns to sign-in',async()=>{
 const ctx=await context();const p=await ctx.newPage();await p.goto(base+'/#/overview');await p.locator('.metric-card').first().waitFor();const csrf=(await (await ctx.request.get(base+'/api/v1/auth/me')).json()).csrf_token;assert.equal((await ctx.request.post(base+'/api/v1/auth/logout',{headers:{'X-CSRF-Token':csrf}})).status(),204);await p.reload();await p.getByRole('heading',{name:'Sign in',exact:true}).waitFor();await ctx.close();
});

for(const lang of ['en','uk','ru'])test(`${lang}: integrations, delivery history, schedules and responsive layouts`,async()=>{
 const ctx=await context(lang);const p=await ctx.newPage();const d=dictionaries[lang];const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base+'/#/integrations');await p.getByRole('heading',{name:d.Integrations,exact:true}).waitFor();await p.locator('.integration-card').first().waitFor();await responsive(p,'integrations',lang);
 const card=p.locator('.integration-card').filter({has:p.getByRole('heading',{name:'Telegram',exact:true})});await card.getByLabel(d['Chat ID'],{exact:true}).fill('-12345');await card.getByLabel(d['Credential environment reference'],{exact:true}).fill('ASTRASYNQ_CREDENTIAL_BROWSER_TEST');await card.getByRole('button',{name:d['Save configuration'],exact:true}).click();await p.getByRole('status').filter({hasText:d['Configuration saved']}).waitFor();await card.getByRole('button',{name:d['Test delivery'],exact:true}).click();await p.getByRole('status').filter({hasText:d['Test queued']}).waitFor();
 await p.goto(base+'/#/deliveries');await p.getByRole('heading',{name:d.Deliveries,exact:true}).waitFor();await p.getByRole('cell',{name:'telegram',exact:true}).first().waitFor();await responsive(p,'deliveries',lang);
 await p.goto(base+'/#/automations');await p.getByRole('heading',{name:d.Automations,exact:true}).waitFor();await p.getByLabel(d.Timezone,{exact:true}).fill('Europe/Kyiv');await p.getByLabel(d.Enabled,{exact:true}).check();await p.getByRole('button',{name:d['Save configuration'],exact:true}).click();await p.getByRole('status').filter({hasText:d['Configuration saved']}).waitFor();await p.reload();await p.getByLabel(d.Timezone,{exact:true}).waitFor();assert.equal(await p.getByLabel(d.Timezone,{exact:true}).inputValue(),'Europe/Kyiv');await responsive(p,'automations',lang);assert.deepEqual(errors,[]);await ctx.close();
});
for(const role of ['viewer','operator'])test(`${role}: integration permissions reflected in new screens`,async()=>{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await loginContext(ctx,role);const p=await ctx.newPage();await p.goto(base+'/#/integrations');await p.getByRole('heading',{name:'Integrations',exact:true}).waitFor();await p.getByLabel('Chat ID',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'Save configuration',exact:true}).count(),0);assert.equal(await p.getByRole('button',{name:'Test delivery',exact:true}).count(),role==='operator'?2:0);assert(await p.getByLabel('Chat ID',{exact:true}).isDisabled());await p.goto(base+'/#/automations');await p.getByLabel('Timezone',{exact:true}).waitFor();assert(await p.getByLabel('Timezone',{exact:true}).isDisabled());await ctx.close();
});



test('M5: keyboard-only login, skip link, profile focus and scrollable table names',async()=>{
 const ctx=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'});const p=await ctx.newPage();await p.goto(base+'/#/login');await p.getByLabel('Email',{exact:true}).waitFor();
 for(let n=0;n<10;n++){if(await p.getByLabel('Email',{exact:true}).evaluate(el=>el===document.activeElement))break;await p.keyboard.press('Tab');}
 assert(await p.getByLabel('Email',{exact:true}).evaluate(el=>el===document.activeElement));await p.keyboard.type('qa-admin@example.test');await p.keyboard.press('Tab');assert(await p.getByLabel('Password',{exact:true}).evaluate(el=>el===document.activeElement));await p.keyboard.type(qaPassword);await p.keyboard.press('Tab');await p.keyboard.press('Enter');await p.locator('.metric-card').first().waitFor();
 await p.reload();await p.locator('.metric-card').first().waitFor();await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Skip to content');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'workspace-content');
 const profile=p.getByLabel('Profile',{exact:true});await profile.focus();assert.equal(await profile.evaluate(el=>getComputedStyle(el).outlineStyle),'solid');
 for(const route of ['deliveries','users']){await p.goto(base+'/#/'+route);await p.getByRole('region',{name:route==='users'?'Users':'Deliveries',exact:true}).waitFor();const region=p.getByRole('region',{name:route==='users'?'Users':'Deliveries',exact:true});assert.equal(await region.getAttribute('tabindex'),'0');await region.focus();assert(await region.evaluate(el=>el===document.activeElement));}
 await ctx.close();
});

test('M5: labels, primary-action contrast and CSP across workspace screens',async()=>{
 const ctx=await context();const p=await ctx.newPage();const violations=[];p.on('console',msg=>{if(msg.type()==='error'&&msg.text().includes('Content Security Policy'))violations.push(msg.text().slice(-300));});
 for(const route of ['overview','import','integrations','deliveries','automations','users']){
  const response=await p.goto(base+'/#/'+route);assert((response?response.headers():(await ctx.request.get(base)).headers())['content-security-policy'].includes("frame-ancestors 'none'"));await p.locator('.workspace-content h1').waitFor();
  if(route==='integrations')await p.getByLabel('Chat ID',{exact:true}).waitFor();if(route==='automations')await p.getByLabel('Timezone',{exact:true}).waitFor();
  const unnamed=await p.locator('input:not([type=hidden]),select,button').evaluateAll(elements=>elements.filter(el=>getComputedStyle(el).display!=='none'&&el.getClientRects().length&&!el.getAttribute('aria-label')&&!el.getAttribute('aria-labelledby')&&!el.labels?.length&&!el.textContent.trim()).map(el=>el.outerHTML));assert.deepEqual(unnamed,[],route);
  const ratios=await p.locator('.button.primary').evaluateAll(elements=>{const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});const lum=s=>{const c=rgb(s);return .2126*c[0]+.7152*c[1]+.0722*c[2];};return elements.filter(el=>!el.disabled).map(el=>{const s=getComputedStyle(el),a=lum(s.color),b=lum(s.backgroundColor);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);});});assert(ratios.every(x=>x>=4.5),route+' primary contrast');
 }
 assert.deepEqual(violations,[]);await ctx.close();
});

test('M5: loading, empty and API failure states',async()=>{
 const ctx=await context();const p=await ctx.newPage();let release;const blocked=new Promise(resolve=>release=resolve);await p.route('**/api/v1/integrations',async route=>{await blocked;await route.fulfill({status:503,json:{detail:{code:'api_unavailable'}}});});
 await p.goto(base+'/#/integrations');await p.getByRole('status').filter({hasText:'Loading session'}).waitFor();release();await p.getByRole('status').filter({hasText:dictionaries.en.api_unavailable}).waitFor();
 await p.route('**/api/v1/deliveries?*',route=>route.fulfill({status:200,json:{items:[],total:0}}));await p.goto(base+'/#/deliveries');await p.getByText('No deliveries yet',{exact:true}).waitFor();await ctx.close();
});
