import {test,before,after,afterEach} from 'node:test';import assert from 'node:assert/strict';import {chromium} from 'playwright';import fs from 'node:fs';
const base=process.env.ASTRASYNQ_IMMERSIVE_URL||'http://127.0.0.1:4191',output=process.env.ASTRASYNQ_IMMERSIVE_OUTPUT||'../.clearance/quality';fs.mkdirSync(output,{recursive:true});let browser;
before(async()=>browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome',headless:true}));after(async()=>browser.close());afterEach(async()=>{for(const c of browser.contexts())await c.close();});
async function page(options={}){const c=await browser.newContext({viewport:{width:1440,height:1000},...options});await c.route('**/api/v1/auth/me',r=>r.fulfill({status:401,json:{detail:{code:'auth_required'}}}));return c.newPage();}
for(const width of [1440,1024,768,390])test(`language menu: keyboard, outside click, persistence and layout ${width}`,async()=>{
 const p=await page({viewport:{width,height:1000},reducedMotion:'reduce',hasTouch:width===390});await p.goto(base);const trigger=p.locator('.language-trigger'),before=await trigger.boundingBox();assert.equal(await trigger.getAttribute('aria-haspopup'),'menu');await trigger.focus();await p.keyboard.press('Enter');assert.equal(await trigger.getAttribute('aria-expanded'),'true');assert.equal(await p.getByRole('menuitemradio').count(),3);assert.equal(await p.getByRole('menuitemradio',{name:'English'}).getAttribute('aria-checked'),'true');assert.deepEqual(await trigger.boundingBox(),before);await p.keyboard.press('End');assert(await p.getByRole('menuitemradio',{name:'Русский'}).evaluate(e=>e===document.activeElement));await p.keyboard.press('Home');await p.keyboard.press('ArrowDown');await p.keyboard.press('Enter');assert.equal(await trigger.getAttribute('aria-expanded'),'false');assert.equal(await p.locator('html').getAttribute('lang'),'uk');assert.equal(await p.evaluate(()=>localStorage.getItem('astrasynq.language')),'uk');assert(await trigger.evaluate(e=>e===document.activeElement));await trigger.click();await p.keyboard.press('Escape');assert.equal(await p.getByRole('menu').count(),0);await trigger.click();await p.locator('h1').click();assert.equal(await p.getByRole('menu').count(),0);await p.reload();assert.equal(await p.locator('html').getAttribute('lang'),'uk');await trigger.click();await p.getByRole('menuitemradio',{name:'Русский'}).click();await trigger.click();await p.screenshot({path:`${output}/language-dropdown-${width}.png`});assert(await trigger.evaluate(e=>{const r=e.getBoundingClientRect();return r.right<=innerWidth&&r.left>innerWidth*.5;}));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
});
for(const lang of ['en','uk','ru'])test(`no technical event identifier anywhere on landing ${lang}`,async()=>{const p=await page({reducedMotion:'reduce'});await p.context().addInitScript(l=>localStorage.setItem('astrasynq.language',l),lang);await p.goto(base);assert(!(await p.locator('.landing').innerText()).includes('import.completed'));assert.equal(await p.locator('[data-story-stage]').count(),7);});
test('poster is decoded while renderer remains blocked; real frame fades in',async()=>{const p=await page();let release;const gate=new Promise(r=>release=r);await p.route('**/CoreScene-*.js',async r=>{await gate;await r.continue();});await p.goto(base,{waitUntil:'domcontentloaded'});await p.locator('.core-fallback img').waitFor();await p.waitForFunction(()=>{const i=document.querySelector('.core-fallback img');return i?.complete&&i.naturalWidth>0;});await p.screenshot({path:`${output}/first-frame.png`});release();await p.locator('.core-visual[data-state="webgl"]').waitFor();await p.locator('.core-fallback').waitFor({state:'detached'});await p.screenshot({path:`${output}/landing.png`});await p.locator('.core-workspace-bridge').evaluate(e=>e.scrollIntoView({block:'start'}));await p.screenshot({path:`${output}/workspace-transition.png`});});
test('mobile Low uses fewer routes and calls, no expensive postprocessing, touch scroll',async()=>{const p=await page({viewport:{width:390,height:1000},isMobile:true,hasTouch:true});await p.goto(base);await p.locator('.core-visual[data-state="webgl"]').waitFor();const c=p.locator('canvas');assert.equal(await c.getAttribute('data-quality'),'low');assert.equal(await c.getAttribute('data-postprocessing'),'off');assert.equal(await c.getAttribute('data-depth-of-field'),'off');assert.equal(await c.getAttribute('data-dpr'),'1');assert(Number(await c.getAttribute('data-draw-calls'))<36);assert.equal(await c.getAttribute('data-route-count'),'64');await p.locator('.language-trigger').tap();await p.getByRole('menuitemradio',{name:'Українська'}).tap();await p.locator('#core-delivery').evaluate(e=>e.scrollIntoView());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`${output}/mobile-story.png`});});
for(const quality of ['high','balanced','low'])test(`quality preset ${quality} retains assembly and interaction`,async()=>{const p=await page();await p.context().addInitScript(q=>window.__ASTRA_PROFILE__={quality:q},quality);await p.goto(base);await p.locator('.core-visual[data-state="webgl"]').waitFor();const c=p.locator('canvas');assert.equal(await c.getAttribute('data-quality'),quality);assert.equal(await c.getAttribute('data-postprocessing'),quality==='low'?'off':'bloom');assert.equal(await c.getAttribute('data-chip-local-pose'),'0,0,0');assert.equal(await c.getAttribute('data-board-local-pose'),'0,0,0');});
test('hardware hints alone do not suppress a capable renderer',async()=>{const p=await page();await p.context().addInitScript(()=>{Object.defineProperty(navigator,'hardwareConcurrency',{get:()=>2});Object.defineProperty(navigator,'deviceMemory',{get:()=>2});});await p.goto(base);await p.locator('.core-visual[data-state="webgl"]').waitFor();assert.equal(await p.locator('[data-story-stage]').count(),7);});
test('observed slow cadence conservatively drops Balanced to Low',async()=>{const p=await page();await p.context().addInitScript(()=>{const raf=window.requestAnimationFrame.bind(window);window.requestAnimationFrame=cb=>raf(()=>setTimeout(()=>cb(performance.now()),75));});await p.goto(base);await p.locator('.core-visual[data-state="webgl"]').waitFor({timeout:30000});await p.waitForFunction(()=>document.querySelector('canvas')?.dataset.quality==='low',{},{timeout:15000});assert.equal(await p.locator('canvas').getAttribute('data-postprocessing'),'off');});
