import {createContext,useContext,useEffect,useState,type ReactNode,type FormEvent} from 'react';
import {request,setCsrf, type Identity} from './api';
import {t,LanguageSwitcher} from './i18n';
import './auth.css';
import {syntheticDemo} from './Demo';
const Context=createContext<{user:Identity|null;refresh:()=>Promise<void>;logout:()=>Promise<void>}>({user:null,refresh:async()=>{},logout:async()=>{}});
export const useAuth=()=>useContext(Context);
export function AuthProvider({children}:{children:ReactNode}){
 const [user,setUser]=useState<Identity|null>(null);const [loading,setLoading]=useState(true);
 const refresh=async()=>{try{const u=await request<Identity>('/auth/me');setCsrf(u.csrf_token);setUser(u);}catch{setCsrf('');setUser(null);}finally{setLoading(false);}};
 useEffect(()=>{void refresh();const expired=()=>{setUser(null);setCsrf('');};window.addEventListener('auth-expired',expired);return()=>window.removeEventListener('auth-expired',expired);},[]);
 const logout=async()=>{await request('/auth/logout',{method:'POST'});setCsrf('');setUser(null);localStorage.removeItem('astrasynq.active-import');window.location.hash='/login';};
 return <Context.Provider value={{user,refresh,logout}}>{loading?<div className="auth-loading" role="status">{t('Loading session…')}</div>:children}</Context.Provider>;
}
export function LoginScreen({expired=false}:{expired?:boolean}){
 const {refresh}=useAuth();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{const pre=await request<{csrf_token:string}>('/auth/csrf');const u=await request<Identity>('/auth/login',{method:'POST',headers:{'X-CSRF-Token':pre.csrf_token},body:JSON.stringify({email,password})});setCsrf(u.csrf_token);setPassword('');localStorage.removeItem('astrasynq.active-import');await refresh();window.location.hash='/overview';}catch(e){setPassword('');setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="auth-page"><div className="auth-nav"><a className="brand" href="#/">AstraSynq.</a><LanguageSwitcher/></div><section className="panel auth-card"><span className="eyebrow dark">{t('Your workspace')}</span><h1>{t('Sign in')}</h1>{expired&&<p role="status">{t('authentication_required')}</p>}<p>{t(syntheticDemo?'Invitation-only synthetic account. Ask the demo owner for temporary access. The first load can take about one minute.':'Use the account created by your workspace administrator.')}</p><form onSubmit={submit}>{error&&<div className="error-banner" role="alert">{t(error)}</div>}<label>{t('Email')}<input type="email" autoComplete="username" required maxLength={320} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t('Password')}<input type="password" autoComplete="current-password" required maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button primary" disabled={busy}>{t(busy?'Signing in…':'Sign in')}</button></form></section></main>;
}
export function ProfileMenu(){const {user,logout}=useAuth();const [error,setError]=useState('');return <details className="profile-menu"><summary aria-label={t('Profile')}><span>{user?.email}</span><span className="pill neutral">{t(user?.role||'')}</span></summary><div><p>{user?.email}</p><button className="button secondary" onClick={()=>logout().catch(e=>setError(e.message))}>{t('Sign out')}</button>{error&&<p role="alert">{t(error)}</p>}</div></details>;}
export function Forbidden(){return <section className="panel auth-card"><h1>403 · {t('Access denied')}</h1><p>{t('Your role does not allow this action.')}</p><a className="button primary" href="#/overview">{t('Back to overview')}</a></section>;}
type Member={id:string;email:string;role:string;active:boolean};
export function UsersScreen(){
 const [rows,setRows]=useState<Member[]>([]);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState('viewer');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [page,setPage]=useState(1);const [total,setTotal]=useState(0);
 const load=()=>request<{items:Member[];total:number}>(`/users?page=${page}`).then(r=>{setRows(r.items);setTotal(r.total);}).catch(e=>setError(e.message));useEffect(()=>{void load();},[page]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await request('/users',{method:'POST',body:JSON.stringify({email,password,role})});setPassword('');setEmail('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function change(u:Member,next:string,active=u.active){setError('');setBusy(true);try{await request(`/users/${u.id}/role`,{method:'PUT',body:JSON.stringify({role:next,active})});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-heading"><div><h1>{t('Users')}</h1><p>{t('Create accounts and manage workspace roles.')}</p></div></div>{error&&<div className="error-banner" role="alert">{t(error)}</div>}<section className="panel users-panel"><h2>{t('Create user')}</h2><form className="user-form" onSubmit={create}><label>{t('Email')}<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} maxLength={320}/></label><label>{t('Temporary password')}<input type="password" autoComplete="new-password" required minLength={12} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>{t('Role')}<select value={role} onChange={e=>setRole(e.target.value)}>{['viewer','operator','admin'].map(r=><option key={r} value={r}>{t(r)}</option>)}</select></label><button className="button primary" disabled={busy}>{t('Create user')}</button></form><p>{t('Password must contain at least 12 characters.')}</p></section><section className="panel users-panel"><div className="table-wrap" role="region" aria-label={t("Users")} tabIndex={0}><table><thead><tr><th>{t('Email')}</th><th>{t('Role')}</th><th>{t('Status')}</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td>{u.email}</td><td><select aria-label={t('Role for {email}',{email:u.email})} disabled={busy} value={u.role} onChange={e=>void change(u,e.target.value)}>{['viewer','operator','admin'].map(r=><option key={r} value={r}>{t(r)}</option>)}</select></td><td><button className="button secondary" disabled={busy} onClick={()=>void change(u,u.role,!u.active)}>{t(u.active?'Deactivate':'Activate')}</button></td></tr>)}</tbody></table></div><div className="wizard-footer"><button className="button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>{t('Previous page')}</button><span>{t('Page {page}',{page})}</span><button className="button secondary" disabled={page*20>=total} onClick={()=>setPage(p=>p+1)}>{t('Next page')}</button></div></section></>;
}
