import {syntheticDemo} from './Demo';
import {useEffect,useState,type FormEvent} from 'react';
import {request} from './api';
import {useAuth} from './Auth';
import {t,formatNumber} from './i18n';
import './integrations.css';
type Config={id:string;kind:string;enabled:boolean;destination:string;credential_ref:string;credential_mask:string;timeout:number;max_attempts:number;backoff:number};
type Delivery={id:string;event_id:string;event_type:string;integration:string;status:string;attempts:number;last_response:string|null;response_code:number|null;next_retry:string|null;created_at:string;updated_at:string;delivered_at:string|null;can_retry:boolean};
const stamp=(s:string|null)=>s?new Date(s).toLocaleString(document.documentElement.lang):'—';
function ConfigCard({kind,config,reload,report}:{kind:string;config?:Config;reload:()=>Promise<void>;report:(s:string)=>void}){
 const {user}=useAuth();const manage=user?.role==='admin';const act=user?.role!=='viewer';
 const [destination,setDestination]=useState('');const [ref,setRef]=useState('');const [enabled,setEnabled]=useState(false);const [timeout,setTimeoutValue]=useState(10);const [attempts,setAttempts]=useState(5);const [backoff,setBackoff]=useState(30);const [busy,setBusy]=useState(false);
 useEffect(()=>{setDestination(config?.destination||'');setRef(config?.credential_ref||'');setEnabled(config?.enabled||false);setTimeoutValue(config?.timeout||10);setAttempts(config?.max_attempts||5);setBackoff(config?.backoff||30);},[config]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);report('');try{await request(`/integrations/${kind}`,{method:'PUT',body:JSON.stringify({enabled,destination,credential_ref:ref,timeout,max_attempts:attempts,backoff})});await reload();report('Configuration saved');}catch(e){report((e as Error).message);}finally{setBusy(false);}}
 async function test(){setBusy(true);report('');try{await request(`/integrations/${kind}/test`,{method:'POST'});report('Test queued');}catch(e){report((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel integration-card"><h2>{kind==='webhook'?'Webhook':'Telegram'}</h2><span className="pill neutral">{t(config?.enabled?'Enabled':'Disabled')}</span><form onSubmit={save}><label>{t(kind==='webhook'?'Endpoint URL':'Chat ID')}<input value={destination} onChange={e=>setDestination(e.target.value)} disabled={!manage} required maxLength={2048}/></label><label>{t('Credential environment reference')}<input value={ref} onChange={e=>setRef(e.target.value)} disabled={!manage} required pattern="ASTRASYNQ_CREDENTIAL_[A-Z0-9_]+" placeholder="ASTRASYNQ_CREDENTIAL_WEBHOOK" maxLength={128}/></label><p>{t('Secret value')} <span aria-label={t('Masked credential')}>{config?.credential_mask||'—'}</span></p><p className="muted">{t(syntheticDemo?'Mock sink only. Telegram and external webhooks are disabled.':'Credentials are supplied to the worker through environment variables.')}</p><div className="policy-fields"><label>{t('Timeout seconds')}<input type="number" min={1} max={20} value={timeout} disabled={!manage} onChange={e=>setTimeoutValue(Number(e.target.value))}/></label><label>{t('Max attempts')}<input type="number" min={1} max={10} value={attempts} disabled={!manage} onChange={e=>setAttempts(Number(e.target.value))}/></label><label>{t('Backoff seconds')}<input type="number" min={1} max={3600} value={backoff} disabled={!manage} onChange={e=>setBackoff(Number(e.target.value))}/></label></div><label className="check-label"><input type="checkbox" checked={enabled} disabled={!manage} onChange={e=>setEnabled(e.target.checked)}/>{t('Enabled')}</label><div className="integration-actions">{manage&&<button className="button primary" disabled={busy}>{t('Save configuration')}</button>}{act&&!syntheticDemo&&<button type="button" className="button secondary" disabled={busy||!config} onClick={()=>void test()}>{t('Test delivery')}</button>}</div></form></section>;
}
export function IntegrationsScreen(){const [loaded,setLoaded]=useState(false);const [configs,setConfigs]=useState<Config[]>([]);const [notice,setNotice]=useState('');const load=async()=>{const r=await request<{items:Config[]}>('/integrations');setConfigs(r.items);setLoaded(true);};useEffect(()=>{load().catch(e=>setNotice(e.message));},[]);return <><div className="page-heading"><div><h1>{t('Integrations')}</h1><p>{t('Deliver events through saved connections.')}</p></div><a href="#/deliveries" className="button secondary">{t('Delivery history')}</a></div>{notice&&<p role="status" className="integration-notice">{t(notice)}</p>}<div className="integration-grid">{!loaded?notice?null:<p role="status">{t("Loading session…")}</p>:['webhook','telegram'].map(kind=><ConfigCard key={kind} kind={kind} config={configs.find(c=>c.kind===kind)} reload={load} report={setNotice}/>)}</div></>;}
export function DeliveriesScreen(){const {user}=useAuth();const [items,setItems]=useState<Delivery[]>([]);const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const load=async()=>{const r=await request<{items:Delivery[];total:number}>(`/deliveries?page=${page}`);setItems(r.items);setTotal(r.total);};useEffect(()=>{void load().catch(e=>setNotice(e.message));const timer=window.setInterval(()=>void load().catch(()=>{}),5000);return()=>clearInterval(timer);},[page]);async function retry(id:string){setBusy(true);try{await request(`/deliveries/${id}/retry`,{method:'POST'});await load();setNotice('Retry queued');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}return <><div className="page-heading"><div><h1>{t('Deliveries')}</h1><p>{t('At-least-once delivery. Receivers should deduplicate by event ID.')}</p></div></div>{notice&&<p role="status">{t(notice)}</p>}<section className="panel integration-card"><div className="table-wrap" role="region" aria-label={t("Deliveries")} tabIndex={0}><table><thead><tr>{['Event','Integration','Status','Attempts','Last response','Next retry','Timestamps','Action'].map(x=><th key={x}>{t(x)}</th>)}</tr></thead><tbody>{items.map(d=><tr key={d.id}><td>{t(d.event_type)}<small className="event-id">{d.event_id}</small></td><td>{d.integration}</td><td>{t(d.status)}</td><td>{formatNumber(d.attempts)}</td><td>{d.response_code||'—'} {d.last_response?t(d.last_response):''}</td><td>{stamp(d.next_retry)}</td><td>{t('Created')}: {stamp(d.created_at)}<br/>{t('Updated')}: {stamp(d.updated_at)}<br/>{t('Delivered')}: {stamp(d.delivered_at)}</td><td>{d.can_retry&&user?.role!=='viewer'&&<button className="button secondary" disabled={busy} onClick={()=>void retry(d.id)}>{t('Retry delivery')}</button>}</td></tr>)}</tbody></table>{!items.length&&<p>{t('No deliveries yet')}</p>}</div><div className="wizard-footer"><button className="button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>{t('Previous page')}</button><span>{t('Page {page}',{page})}</span><button className="button secondary" disabled={page*20>=total} onClick={()=>setPage(p=>p+1)}>{t('Next page')}</button></div></section></>;}
export function AutomationsScreen(){const {user}=useAuth();const [loaded,setLoaded]=useState(false);const [enabled,setEnabled]=useState(false);const [zone,setZone]=useState('UTC');const [next,setNext]=useState<string|null>(null);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{request<{enabled:boolean;timezone:string;next_run_at:string|null}>('/automations').then(s=>{setEnabled(s.enabled);setZone(s.timezone);setNext(s.next_run_at);setLoaded(true);}).catch(e=>{setNotice(e.message);setLoaded(true);});},[]);async function save(e:FormEvent){e.preventDefault();setBusy(true);try{const s=await request<{next_run_at:string}>('/automations/daily-summary',{method:'PUT',body:JSON.stringify({enabled,timezone:zone})});setNext(s.next_run_at);setNotice('Configuration saved');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}if(!loaded)return <p role="status">{t("Loading session…")}</p>;return <><div className="page-heading"><div><h1>{t('Automations')}</h1><p>{t('Daily summary at 09:00 in your selected timezone.')}</p></div></div>{notice&&<p role="status">{t(notice)}</p>}<section className="panel integration-card"><h2>{t('Daily summary')}</h2><form onSubmit={save}><label>{t('Timezone')}<input value={zone} disabled={user?.role!=='admin'} onChange={e=>setZone(e.target.value)} required maxLength={64} placeholder="Europe/Kyiv"/></label><label className="check-label"><input type="checkbox" checked={enabled} disabled={user?.role!=='admin'} onChange={e=>setEnabled(e.target.checked)}/>{t('Enabled')}</label><p>{t('Next run')}: {enabled?stamp(next):t('Disabled')}</p>{user?.role==='admin'&&<button className="button primary" disabled={busy}>{t('Save configuration')}</button>}</form></section></>;}
export function AutomationMetrics(){const [data,setData]=useState<{deliveries:Record<string,number>;enabled_schedules:number;last_worker_activity:string|null;worker_alive:boolean;oldest_due_age_seconds:number}|null>(null);useEffect(()=>{request('/automation-metrics').then(x=>setData(x as typeof data)).catch(()=>{});},[]);return <div className="automation-metrics"><a href="#/deliveries">{t('Deliveries')}: {formatNumber(data?.deliveries.delivered||0)} {t('delivered')} · {formatNumber(data?.deliveries.failed||0)} {t('failed')} · {formatNumber((data?.deliveries.queued||0)+(data?.deliveries.retry||0)+(data?.deliveries.running||0))} {t('Pending')}</a><a href="#/automations">{t('Active schedules')}: {formatNumber(data?.enabled_schedules||0)}</a><span>{syntheticDemo?t('Mock deliveries finish during commit. No persistent worker.'): <>{t('Worker activity')}: {stamp(data?.last_worker_activity||null)} {data&&!data.worker_alive&&t('Worker unavailable')}</>}</span><span>{t('Queue age seconds')}: {formatNumber(data?.oldest_due_age_seconds||0)}</span></div>;}

